# Notebook 04: Full End-to-End Fine-Tuning

In this notebook, we perform true end-to-end training. **All weights of the Moirai encoder and the classification heads are updated**.

In [13]:
import torch
import pandas as pd
from IPython.display import display

from heads import (
    MeanPoolingClassifier,
    SingleScaleAttentionClassifier,
    SingleScaleMultiHeadClassifier,
    HierarchicalMultiHeadClassifier,
)
from models import FullMaskOnlyWrapper, FullHeadWrapper
from utils import get_lsst_dataloaders, universal_grid_search

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
NUM_VARS = 6
SIZE = "small"
PATCH_SIZES = [8, 16, 32, 64]

lr_grid = [5*1e-5]
wd_grid = [0.01, 0.05]

BATCH_SIZE = 256

In [14]:
tr_loader, va_loader, te_loader, num_classes = get_lsst_dataloaders(BATCH_SIZE, DEVICE)

In [15]:
METRICS_COLS = ["Accuracy", "Macro Precision", "Macro Recall", "Macro F1", "Weighted Precision", "Weighted Recall", "Weighted F1"]
df_patch_8_metrics = pd.DataFrame(columns=METRICS_COLS)
df_patch_8_metrics.index.name = "Model"

## 1. Baseline: Linear Model on Mask Embedding Only (Full FT)

In [16]:
df_mask_only = pd.DataFrame(index=["Mask Only"], columns=PATCH_SIZES)
df_mask_only.columns.name = "Patch Size"

for patch in PATCH_SIZES:
    _, metrics = universal_grid_search(
        model_class=FullMaskOnlyWrapper,
        model_kwargs={"patch_size": patch, "num_vars": NUM_VARS, "num_classes": num_classes, "size": SIZE},
        train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
        wd_grid=wd_grid, lr_grid=lr_grid, verbose=True
    )
    df_mask_only.loc["Mask Only", patch] = metrics["Accuracy"]
    if patch == 8:
        df_patch_8_metrics.loc["Mask Only"] = metrics

LR=5e-05| WD=0.01
1.99163513067292
1.6944800072569188
1.5109288518021746
1.3895991682037105
1.3134967456988202
1.2564845104527667
1.2271249565651747
1.2311561291779929
1.2168133365429514
1.2088834929272412
1.2286442663611434
1.248081850811718
1.255764082195313
1.2748007628975846
1.308206302363698
 Early stopping : 14
Val Loss: 1.2089
LR=5e-05| WD=0.05
1.9659802758596776
1.7163413268763845
1.5288995514071084
1.4253127497386158
1.3445464750615561
1.3018999632781114
1.2637897613571911
1.252158387889707
1.2292636109561454
1.2396514270363785
1.2187249049907778
1.2586575833762563
1.2356862789247094
1.2399167200414145
1.2703512170450475
1.2672382554387658
 Early stopping : 15
Val Loss: 1.2187
LR=5e-05| WD=0.01
2.020311820797804
1.7466934570452062
1.5526140278917018
1.4413792961012057
1.354346293744033
1.3059315264709597
1.28584895967468
1.2581725857122157
1.2692044924914352
1.273002579929383
1.2968433698018391
1.3320042893169373
1.3385828181010921
 Early stopping : 12
Val Loss: 1.2582
LR=5e-05| WD=0.05
1.979977061108845
1.7480548242243326
1.5522367440588105
1.4188457737124063
1.3387717851778356
1.2893246654572526
1.2515511716284402
1.2354892831507738
1.2311862687754438
1.2367531536071281
1.2503378265272311
1.2855144458088448
1.308391360732598
1.313272929773098
 Early stopping : 13
Val Loss: 1.2312
LR=5e-05| WD=0.01
1.9704552791952117
1.7247152561094703
1.551213887648854
1.441686295881504
1.3506491174542807
1.2983373762146244
1.271656142986887
1.2664262977072862
1.2740537306157553
1.3001236537607705
1.3079262768349997
1.3318523381783711
1.3583837321134118
 Early stopping : 12
Val Loss: 1.2664
LR=5e-05| WD=0.05
1.9666121316149952
1.6932210321348857
1.5294636274740947
1.412748260226676
1.347375458818141
1.31271954959001
1.2767909532640038
1.2596602624024802
1.2559714637151578
1.270042577410132
1.291024123750082
1.3149538350299121
1.3271857635761664
1.3533360434741508
 Early stopping : 13
Val Loss: 1.2560
LR=5e-05| WD=0.01
1.9240195528278505
1.6323137603154996
1.452379436027713
1.3201010217511557
1.2547378540039062
1.2179683950858387
1.1965895755504206
1.2271268222390153
1.2022320497326735
1.2258159552163226
1.247047858509591
1.201817089949197
 Early stopping : 11
Val Loss: 1.1966
LR=5e-05| WD=0.05
1.8497269347431213
1.5775890602328912
1.4217774092666502
1.3475680913382428
1.2842032085589277
1.2577573506812738
1.2219568394063933
1.2131174492642163
1.234424384628854
1.251679266371378
1.2626238402312364
1.2543124658305471
1.2864797454539354
 Early stopping : 12
Val Loss: 1.2131

In [17]:
print("Mask Only - Accuracy")
display(df_mask_only.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

Mask Only - Accuracy

Patch Size      8       16      32      64
Mask Only   0.6172  0.6115  0.6046  0.6071

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6172,0.4618,0.3446,0.3498,0.5675,0.6172,0.5657

## 2. Baseline: Mean Pooling

In [18]:
df_mean_pool = pd.DataFrame(index=["Mean Pooling"], columns=PATCH_SIZES)
df_mean_pool.columns.name = "Patch Size"

for patch in PATCH_SIZES:
    _, metrics = universal_grid_search(
        model_class=FullHeadWrapper,
        model_kwargs={
            "head_class": MeanPoolingClassifier,
            "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes},
            "patch_size": patch, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
        },
        train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
        wd_grid=wd_grid, lr_grid=lr_grid, verbose=True
    )
    df_mean_pool.loc["Mean Pooling", patch] = metrics["Accuracy"]
    if patch == 8:
        df_patch_8_metrics.loc["Mean Pooling"] = metrics

LR=5e-05| WD=0.01
1.98967732646601
1.6856873791392257
1.4975995174268397
1.376245954172398
1.2937133283149906
1.2265407806489526
1.188662949616347
1.146014923971843
1.1316695872361098
1.1057425989368097
1.1078848548051787
1.118649358671855
1.113788842185726
1.1160762251877203
1.1319558872439996
 Early stopping : 14
Val Loss: 1.1057
LR=5e-05| WD=0.05
2.0296942431752276
1.7406290498206285
1.5239129018008224
1.3922003304086081
1.3130336185780966
1.2288164065136173
1.1914966736382586
1.162642339380776
1.141283253344094
1.1275136645247297
1.1173694986638014
1.106620026797783
1.118584286875841
1.1210955972593974
1.1153169695923968
1.1819519802806824
1.2004383860564813
 Early stopping : 16
Val Loss: 1.1066
LR=5e-05| WD=0.01
2.0026083283308074
1.7317185014244016
1.535494533980765
1.3986073170250994
1.3037317593892415
1.2459205166111147
1.220081715079827
1.1790959457071817
1.1733618567629558
1.1922586206498185
1.234082970192762
1.1988577503498976
1.21543359174961
1.2639684240992477
 Early stopping : 13
Val Loss: 1.1734
LR=5e-05| WD=0.05
2.0207250428393606
1.7306515899130968
1.5239825791459742
1.4047515150008163
1.3021063542947537
1.2357888686947707
1.2065614791420418
1.1853768098645094
1.1826161931200725
1.19559706226597
1.1838236184624154
1.2408900280308917
1.2681022426946376
1.2807352426575451
 Early stopping : 13
Val Loss: 1.1826
LR=5e-05| WD=0.01
1.9302497724207437
1.7180018599440412
1.5575517755213792
1.419868782283814
1.322433702344817
1.275807521207546
1.2169129315430556
1.191163061110954
1.200204121388071
1.1879296157418229
1.2091126354729258
1.193364273241865
1.2590009652502168
1.2722746182263382
1.3006619428231465
 Early stopping : 14
Val Loss: 1.1879
LR=5e-05| WD=0.05
2.094464350522049
1.752735532396208
1.5369377213764965
1.4100477104264546
1.2933817161777155
1.24852188428243
1.1802153325662381
1.1428798727872895
1.1469754252007338
1.1018222773947366
1.1028704226501589
1.103109611728327
1.1136814947050762
1.1280349522102169
1.1407019801256133
 Early stopping : 14
Val Loss: 1.1018
LR=5e-05| WD=0.01
1.8821187077499018
1.5828891081538627
1.412442024161176
1.322592074308938
1.235870707325819
1.1985726695719774
1.1653974676519874
1.1569236681713322
1.145485996230831
1.1493802409831102
1.1579321206100588
1.1680253724741743
1.1674096749080876
1.2049475927663043
 Early stopping : 13
Val Loss: 1.1455
LR=5e-05| WD=0.05
1.8332017059248638
1.5214274462645616
1.3691024373217326
1.2852270671022616
1.2496444830080358
1.1898020757892267
1.1848652973407652
1.17791322382485
1.1652269576623189
1.1636105320317958
1.186833816815198
1.2106828311594522
1.2008382450274335
1.254492522255192
1.2576105313572457
 Early stopping : 14
Val Loss: 1.1636

In [19]:
print("Mean Pooling - Accuracy")
display(df_mean_pool.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

Mean Pooling - Accuracy

Patch Size        8       16      32     64
Mean Pooling  0.6318  0.6241  0.6298  0.631

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6172,0.4618,0.3446,0.3498,0.5675,0.6172,0.5657
Mean Pooling,0.6318,0.4730,0.3573,0.3533,0.5702,0.6318,0.5624

## 3. Advanced Pooling: Attention & MHA (Full FT)

In [20]:
PATCH_SIZES_TO_TEST = [8, 16, 32, 64]
MODES = ["shared_context", "independent_context"]
NUM_HEADS = 16

model_names_single = ["Attention (Base)", f"MHA (Heads={NUM_HEADS})"]
index_single = pd.MultiIndex.from_product([model_names_single, MODES], names=["Model", "Mode"])
df_adv_single = pd.DataFrame(index=index_single, columns=PATCH_SIZES_TO_TEST)
df_adv_single.columns.name = "Patch Size"

for patch in PATCH_SIZES_TO_TEST:
    for mode in MODES:
        # 1. Basic Attention
        _, metrics_attn = universal_grid_search(
            model_class=FullHeadWrapper,
            model_kwargs={
                "head_class": SingleScaleAttentionClassifier,
                "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes, "mode": mode},
                "patch_size": patch, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
            },
            train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
            wd_grid=wd_grid, lr_grid=lr_grid
        )
        df_adv_single.loc[("Attention (Base)", mode), patch] = metrics_attn["Accuracy"]
        if patch == 8:
            df_patch_8_metrics.loc[f"Attention ({mode})"] = metrics_attn

        # 2. Multi-Head Attention
        _, metrics_mha = universal_grid_search(
            model_class=FullHeadWrapper,
            model_kwargs={
                "head_class": SingleScaleMultiHeadClassifier,
                "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes, "patch_mode": mode, "num_heads": NUM_HEADS},
                "patch_size": patch, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
            },
            train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
            wd_grid=wd_grid, lr_grid=lr_grid
        )
        df_adv_single.loc[(f"MHA (Heads={NUM_HEADS})", mode), patch] = metrics_mha["Accuracy"]

print("Attention & MHA - Accuracy")
display(df_adv_single.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

LR=5e-05| WD=0.01
 Early stopping : 15
Val Loss: 1.1589
LR=5e-05| WD=0.05
 Early stopping : 15
Val Loss: 1.1154
LR=5e-05| WD=0.01
 Early stopping : 15
Val Loss: 1.1249
LR=5e-05| WD=0.05

KeyboardInterrupt:

## 4. Ablation Study: Number of Attention Heads

In [ ]:
HEADS_TO_TEST = [16, 32, 64, 128]

df_heads_ablation8 = pd.DataFrame(index=MODES, columns=HEADS_TO_TEST)
df_heads_ablation8.index.name = "Mode"
df_heads_ablation8.columns.name = "Num Heads (Patch 8)"
df_heads_ablation16 = pd.DataFrame(index=MODES, columns=HEADS_TO_TEST)
df_heads_ablation16.index.name = "Mode"
df_heads_ablation16.columns.name = "Num Heads (Patch 16)"

for PATCH in [8, 16]:
    for mode in MODES:
        for heads in HEADS_TO_TEST:
            _, metrics = universal_grid_search(
                model_class=FullHeadWrapper,
                model_kwargs={
                    "head_class": SingleScaleMultiHeadClassifier,
                    "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes, "patch_mode": mode, "num_heads": heads},
                    "patch_size": PATCH, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
                },
                train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
                wd_grid=wd_grid, lr_grid=lr_grid, verbose=True
            )
            if PATCH == 8:
                df_heads_ablation8.loc[mode, heads] = metrics["Accuracy"]
                df_patch_8_metrics.loc[f"MHA-{heads} ({mode})"] = metrics
            else:
                df_heads_ablation16.loc[mode, heads] = metrics["Accuracy"]

LR=0.0001| WD=0.05
1.8792030946995184
1.587150946865237
1.3727774503754406
1.2533731005056117
1.2024532643760122
1.1295714349281498
1.1120942540285064
1.0980616110127146
1.1063881240239957
1.1157859486293018
1.1964236391269094
1.2842744298097564
1.4340674722097753
 Early stopping : 12
Val Loss: 1.0981
LR=0.0001| WD=0.05
1.9495068003491658
1.574629487060919
1.3791399632042987
1.3061113260625823
1.2286659430682174
1.1426450266101496
1.1761039224097398
1.1324723590680255
1.096756697670231
1.1422289600217246
1.1594579966087653
1.2534034320009433
1.2797474570390655
1.4661017792011664
 Early stopping : 13
Val Loss: 1.0968
LR=0.0001| WD=0.05
1.9351809577244083
1.554339984568154
1.35819765998096
1.2449165747417668
1.1559496265116747
1.1580696832842943
1.1797341573529128
1.1181464563540326
1.1252768272306861
1.187676118641365
1.1802993809304587
1.2340882464153011
1.3137529661984948
 Early stopping : 12
Val Loss: 1.1181
LR=0.0001| WD=0.05
1.9458519685559157
1.5944017637066725
1.3478356309053374
1.24234768045627
1.1911645362047645
1.1097162845658093
1.0998655363796204
1.1339843215011969
1.0884879275066097
1.0711383955265448
1.1080461488506659
1.2132912951756298
1.2553011508491951
1.3904802896142976
1.4842385199011825
 Early stopping : 14
Val Loss: 1.0711
LR=0.0001| WD=0.05
1.8591938900753735
1.5961254437764485
1.3794708688084671
1.2726203745942775
1.180925965309143
1.1298658256608296
1.164575510877904
1.1321691546013686
1.1053752288585756
1.1384497987545603
1.132890025774638
1.207598813181001
1.2107333158089864
1.3520418570293644
 Early stopping : 13
Val Loss: 1.1054
LR=0.0001| WD=0.05
1.8658747605191983
1.4927478175822313
1.2987450632622572
1.1843589912585126
1.182561009880004
1.1042824954521366
1.0598512771652966
1.1890485819762315
1.0937875693406516
1.107132588944784
1.2405272644709766
1.189407988292415
 Early stopping : 11
Val Loss: 1.0599
LR=0.0001| WD=0.05
1.8092998518207208
1.5348000419818288
1.396196947834356
1.2826643135489486
1.1818211747378837
1.1463082253448362
1.0870690200386979
1.073174327369628
1.0700387770567483
1.0789143118431899
1.1421374760992158
1.2168945752508271
1.3211661761369162
1.4562074042917268
 Early stopping : 13
Val Loss: 1.0700
LR=0.0001| WD=0.05
1.7696529365167386
1.4881094122320655
1.3256858209284341
1.3068055941806576
1.1743514644421214
1.0884318429280102
1.0838265225170105
1.0971173348465586
1.0561335503570433
1.1206952682355555
1.1443197853196927
1.2558500708603277
1.318652118124613
1.3552218200714607
 Early stopping : 13
Val Loss: 1.0561
LR=0.0001| WD=0.05
1.874956125166358
1.5256117088038748
1.3725280684184253
1.2365558767706397
1.1682815745594055
1.1308957289874069
1.1562340530922743
1.1140042591870316
1.097570835090265
1.2064111484744684
1.2746992683022973
1.425527060904154
1.602945839486471
1.6517463893425175
 Early stopping : 13
Val Loss: 1.0976
LR=0.0001| WD=0.05
1.8966348995038165
1.5622551043828328
1.361642379101699
1.2661380186313536
1.1984770404614085
1.1444049521190365
1.1266846453271262
1.0911638940252908
1.188783251173128
1.2505455782743005
1.4443905392313392
1.4948555754452217
1.6562959643883435
 Early stopping : 12
Val Loss: 1.0912
LR=0.0001| WD=0.05
1.9287077295101756
1.572111452498087
1.3555093208948772
1.2569045797596132
1.198542289617585
1.136362632115682
1.1105522692688112
1.1424904005314276
1.1902573166823969
1.2725439294566954
1.3929705687654697
1.5519325035374338
 Early stopping : 11
Val Loss: 1.1106
LR=0.0001| WD=0.05
1.908876459772994
1.6397874326240727
1.3685616254806519
1.259219344069318
1.1471941170653677
1.1383493343989055
1.1099074429612819
1.1344129816303408
1.2538114708613575
1.3667209070872486
1.4612510340000555
1.5917255316323382
 Early stopping : 11
Val Loss: 1.1099
LR=0.0001| WD=0.05
1.9418940069229622
1.6376232248011644
1.401945023032708
1.2587191118457453
1.2011558757564886
1.1787966218421129
1.1123821812916577
1.1190765776285312
1.1506956137292754
1.2301628046888646
1.42240334429392
1.59646343797203
 Early stopping : 11
Val Loss: 1.1124
LR=0.0001| WD=0.05
1.9052431505870044
1.5958145440109377
1.3748504262629564
1.2218687049741668
1.1380977572464361
1.096379733667141
1.1360835864291927
1.0825547357884848
1.1297631370342844
1.1366966652676342
1.343222019149036
1.3700645919737777
1.5766751601444027
 Early stopping : 12
Val Loss: 1.0826
LR=0.0001| WD=0.05
1.9573877158203745
1.637056805253998
1.3875214103760758
1.2776576154600314
1.2145673598700422
1.1798865359003952
1.103453844543395
1.127335894398573
1.0837159864301604
1.144586066889569
1.2468907474502315
1.461940225546922
1.4895181946638154
1.5739192739734804
 Early stopping : 13
Val Loss: 1.0837
LR=0.0001| WD=0.05
1.7786280915019959
1.4831446787206137
1.3449579351316623
1.2182264395845614
1.137236323783068
1.0900739828745525
1.0657476351513127
1.1031253134332053
1.118998979165302
1.1770144264872482
1.394981115814147
1.4276005465809891
 Early stopping : 11
Val Loss: 1.0657

In [ ]:
print("Ablation: Num Heads (Patch = 8) - Accuracy")
display(df_heads_ablation8.astype(float).round(4))
print("Ablation: Num Heads (Patch = 16) - Accuracy")
display(df_heads_ablation16.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

Ablation: Num Heads (Patch = 8) - Accuracy

Num Heads (Patch 8)     16      32      64      128
Mode
shared_context       0.6237  0.6480  0.6277  0.6334
independent_context  0.6371  0.6436  0.6403  0.6391

Ablation: Num Heads (Patch = 16) - Accuracy

Num Heads (Patch 16)     16      32      64      128
Mode
shared_context        0.6273  0.6310  0.6419  0.6290
independent_context   0.6277  0.6395  0.6375  0.6391

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6196,0.4389,0.3398,0.3444,0.5618,0.6196,0.5624
Mean Pooling,0.6565,0.4276,0.3789,0.3802,0.5860,0.6565,0.6031
Attention (shared_context),0.6269,0.4200,0.3758,0.3693,0.5634,0.6269,0.5781
Attention (independent_context),0.6387,0.4777,0.3733,0.3738,0.5791,0.6387,0.5848
MHA-16 (shared_context),0.6237,0.3861,0.3634,0.3552,0.5479,0.6237,0.5652
MHA-32 (shared_context),0.6480,0.4111,0.3815,0.3790,0.5760,0.6480,0.5950
MHA-64 (shared_context),0.6277,0.4512,0.3739,0.3780,0.5675,0.6277,0.5691
MHA-128 (shared_context),0.6334,0.4648,0.3835,0.3834,0.5869,0.6334,0.5977
MHA-16 (independent_context),0.6371,0.4089,0.3724,0.3731,0.5707,0.6371,0.5851
MHA-32 (independent_context),0.6436,0.4205,0.3802,0.3781,0.5744,0.6436,0.5945
MHA-64 (independent_context),0.6403,0.4518,0.3776,0.3830,0.5678,0.6403,0.5913
MHA-128 (independent_context),0.6391,0.4718,0.3981,0.4041,0.5776,0.6391,0.5996

## 5. Hierarchical MHA (Full FT)

In [ ]:
df_hierarchical = pd.DataFrame(index=MODES, columns=PATCH_SIZES_TO_TEST)
df_hierarchical.index.name = "Mode"
df_hierarchical.columns.name = "Patch Size"

for patch in PATCH_SIZES_TO_TEST:
    for mode in MODES:
        _, metrics_hier = universal_grid_search(
            model_class=FullHeadWrapper,
            model_kwargs={
                "head_class": HierarchicalMultiHeadClassifier,
                "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes, "patch_mode": mode, "num_heads": NUM_HEADS},
                "patch_size": patch, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
            },
            train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
            wd_grid=wd_grid, lr_grid=lr_grid
        )
        df_hierarchical.loc[mode, patch] = metrics_hier["Accuracy"]
        if patch == 8:
            df_patch_8_metrics.loc[f"Hierarchical ({mode})"] = metrics_hier

LR=0.0001| WD=0.05
 Early stopping : 15
Val Loss: 1.2529
LR=0.0001| WD=0.05
 Early stopping : 13
Val Loss: 1.2223
LR=0.0001| WD=0.05
 Early stopping : 13
Val Loss: 1.2558
LR=0.0001| WD=0.05
 Early stopping : 12
Val Loss: 1.2814
LR=0.0001| WD=0.05
 Early stopping : 12
Val Loss: 1.2924
LR=0.0001| WD=0.05
 Early stopping : 14
Val Loss: 1.2507
LR=0.0001| WD=0.05
 Early stopping : 13
Val Loss: 1.2847
LR=0.0001| WD=0.05
 Early stopping : 11
Val Loss: 1.2634

In [ ]:
print("Hierarchical MHA - Accuracy")
display(df_hierarchical.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

Hierarchical MHA - Accuracy

Patch Size               8       16      32      64
Mode
shared_context       0.6148  0.5994  0.5795  0.5876
independent_context  0.5973  0.5848  0.5904  0.5961

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6196,0.4389,0.3398,0.3444,0.5618,0.6196,0.5624
Mean Pooling,0.6565,0.4276,0.3789,0.3802,0.5860,0.6565,0.6031
Attention (shared_context),0.6269,0.4200,0.3758,0.3693,0.5634,0.6269,0.5781
Attention (independent_context),0.6387,0.4777,0.3733,0.3738,0.5791,0.6387,0.5848
MHA-16 (shared_context),0.6237,0.3861,0.3634,0.3552,0.5479,0.6237,0.5652
MHA-32 (shared_context),0.6480,0.4111,0.3815,0.3790,0.5760,0.6480,0.5950
MHA-64 (shared_context),0.6277,0.4512,0.3739,0.3780,0.5675,0.6277,0.5691
MHA-128 (shared_context),0.6334,0.4648,0.3835,0.3834,0.5869,0.6334,0.5977
MHA-16 (independent_context),0.6371,0.4089,0.3724,0.3731,0.5707,0.6371,0.5851
MHA-32 (independent_context),0.6436,0.4205,0.3802,0.3781,0.5744,0.6436,0.5945
MHA-64 (independent_context),0.6403,0.4518,0.3776,0.3830,0.5678,0.6403,0.5913
MHA-128 (independent_context),0.6391,0.4718,0.3981,0.4041,0.5776,0.6391,0.5996
Hierarchical (shared_context),0.6148,0.3535,0.3335,0.3261,0.5215,0.6148,0.5526
Hierarchical (independent_context),0.5973,0.3201,0.3422,0.3271,0.4940,0.5973,0.5371